apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ServiceMonitor
      name: ml-namespace-metrics
    patch: |-
      - op: replace
        path: /spec/endpoints/0/interval
        value: 15s
