apiVersion: v1
kind: Pod
metadata:
  name: vault-injected-demo
  namespace: ml-alpha-prod
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ml-alpha-prod"
    vault.hashicorp.com/agent-inject-secret-app: "kv/data/ml-alpha-prod/app"
spec:
  serviceAccountName: ml-workload
  containers:
    - name: app
      image: ghcr.io/company/demo:1.0.0
      command: ["/bin/sh", "-c", "sleep 3600"]
