apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  labels:
    app: vllm-server
    zonaas/workload-type: llm
spec:
  type: ClusterIP
  selector:
    app: vllm-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000