apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${NAME}
  description: ML project scaffolded by ML-LZ
  labels:
    zonaas/cost-center: ${COSTCENTER}
    zonaas/gpu-profile: ${GPUPROFILE}
    zonaas/sla-tier: ${SLATIER}
    zonaas/compliance-level: ${COMPLIANCELEVEL}
spec:
  type: service
  owner: ${OWNER}
  lifecycle: production
